### PR TITLE
Update Core.java

### PR DESCRIPTION
**Pull request by Mikerman50**
added hardcoded mcmod.info file.

glad to see other users out there using REAL ores

### CODE REVIEW

**Comment by Cendrb** [comment]
Thanks man, didn't know you could do that

**Comment by Mikerman50** [comment]
you're welcome,  I'm impressed with the way of setting the ore generate in 1.9, Used to do that in 1.6.4 but lost the will to update after them repeated updates, Btw I'm working on [Simcraft](http://www.planetminecraft.com/mod/simcraft-1118558/)

**Comment by zenMaya** [comment]
By the way, how do you find us? :)

**Comment by Mikerman50** [comment]
Well as I'm attempting to update the mod I done a search for some of the ore names that we used. Found a couple of people that stole our textures. Weve had then since 1.2.5 beta lol. But yeah seen that you had the same ore names as us. Hopefully we'll be using a compatible energy system.

**Comment by zenMaya** [comment]
We planned to use Redstone Flux. For us is textures a big question, because nobody wants to do them :) Our mod will contaim more than just ores and their processing. We also planned chipsets and some energy productive blocks, so our mod will be playable as standalone.

Yor mod is pretty cool, but i think you got into a trap, with that much blocks.

**Comment by Mikerman50** [comment]
Thanks. Simcraft was designed to be a decorative mod originally with aspects of real life  and hard work the masonry bench you have to repeatedly click to make some of the reinforced blocks which are as strong as obsidian. I noticed that you are using fixed floats in the generic block. Do you plan on setting your own so they can sustain a certain  level of tnt mining?

**Comment by Cendrb** [comment]
We haven't really thought about something like TNT mining, but it might be a good idea to give our ores some at least a bit realistic explosion resistance values.

To the oregen: We aren't sure if this is the way to do it. We just took a tutorial for 1.8 and changed it to work with 1.9.
Btw we also want to make some of the ores generate together in veins. We thought about generating the others in the existing ones (just replacing them), but that doesn't seem effective. Do you know some better way to do it?

**Comment by Mikerman50** [comment]
I haven't experimented with mixed ore veins. But they way you have it in your ore gen currently would work maybe better if you increased the cluster size. So there is more to replace.. maybe there is a way not to use the random function and replace it with a set variable which represents a shape.

**Pull request merged**
